language: python
sudo: false
branches:
  only:
    - master
    - /^\d\.\d+$/
    - /^\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=jessie
    - python: 2.7
      env: TOXENV=pypy
    - python: 2.7
      env: TOXENV=pypy3
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.6
      env: TOXENV=docs
install:
  - |
      if [ "$TOXENV" = "pypy" ]; then
        export PYPY_VERSION="pypy-6.0.0-linux_x86_64-portable"
        wget "https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2"
        tar -jxf ${PYPY_VERSION}.tar.bz2
        virtualenv --python="$PYPY_VERSION/bin/pypy" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
      if [ "$TOXENV" = "pypy3" ]; then
        export PYPY_VERSION="pypy3.5-5.9-beta-linux_x86_64-portable"
        wget "https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2"
        tar -jxf ${PYPY_VERSION}.tar.bz2
        virtualenv --python="$PYPY_VERSION/bin/pypy3" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
  - pip install -U tox twine wheel codecov

script: tox
after_success:
  - codecov
notifications:
  slack:
    rooms:
      - secure: zsDJgHzhPoAIs8OsOiv5wmNsck++hjZljeYAfKh25UwW8X97Rqvq5r9LMlQzIHf2a638AbsubDNeSbrxxu6cFDeeIFngG1EO5mOSWzKr18LM5pFb0GVlImKzZpKgLqKmaD5ATYXnvUaHjEHgO45TzjIsbwo9P4vRU5C/lGYwfdv/J82hP0OUo02HqWGkwpG0aeuzs1bJZKjS/RdHROt0SQpRfVB8hi4HHrQILgliuVcpvIk46FgRB49VmzpAGuQfJtB06gj8o6tL/1JlXQ9/ElrHwEJyGjiyeP/nP8qit+i9TTlHGT9k0s9oYuXWM8OlgKfKE13Mo8fVRaAhVv9DRcwtNpX5M0RtC5bEjCPQIL14ky4ymeSlGchmy37jTKJCNHm4St4CtodCrF5J77h8Gkjx9tkZOhf4Rd8veMMgv/gj8pyt3asJ8PMDvREjF4n4mRPy5SB53anEhrFXE801KOpqb4Ffsjv2DBJmuAId+OmHLs69jHeiwxkBDaeKDr6rpiiKQaZNbDw5KxjEafEtclVmSdprq57Og2SPaCR1TrUu3SVyUjVoWNj6olKS9ALoiDAVLBprbyBsSS9gYwfTlSBNxCsMApQksjmo0/S6n/FwyCvn4AZZVziLVtVxPBY0sUpRBNySkTTrQzpCiEPNmv7tU8d0ZcVI508/WALzIQ0=
cache:
  directories:
    - $HOME/.cache/pip
# deploy:
#   provider: pypi
#   distributions: "sdist bdist_wheel"
#   user: scrapy
#   password:
#     secure: JaAKcy1AXWXDK3LXdjOtKyaVPCSFoCGCnW15g4f65E/8Fsi9ZzDfmBa4Equs3IQb/vs/if2SVrzJSr7arN7r9Z38Iv1mUXHkFAyA3Ym8mThfABBzzcUWEQhIHrCX0Tdlx9wQkkhs+PZhorlmRS4gg5s6DzPaeA2g8SCgmlRmFfA=
#   on:
#     tags: true
#     repo: scrapy/scrapy
#     condition: "$TOXENV == py27 && $TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: grammy.jiang
  password:
    secure: weU3PkUSAL8jAwG84z1GiBMLL77E296L7l4GDYB8ufZoMG9auO5FdPnYFmlMvIKfP//J9fxyYFepmQYimYZFaeEmxpICdxcNka7srry3QCZgVaIVVH3bUkkx1/qw+EAHtVX9LbQL0ZpeDvagrLVfO80TXYqzKzFpr7U3a0ao8ZRHPWB59MQMP8UNsk4u/GT5criNUpcD1eMp5ciyK2Ph7v0OQPxhoqXlscAoDRFKUIkZFfk/C/JjMOqWXgG0PKnphW9xk/VRpG8kgoyFZ52AAzwGPqqctTXd2uraEa6+YvFtI972lQBGV2jg8sRnt+rKDRggkI/tFLL9PT1CXm9Wi/6n1MSYHN9LycIeqqp0er+S3BguL4z4MGgb+lMnTWbkvyyX9HcbgSpm+W1gNSDE5KZUFEes0ErbKm/egcDJMyd5f8IwYKihZrHSDkRkAZkaW32R3YHLnQjsYJn0lSy376IJ4DzcoYJejJM1UvVuikO43zDxggbwJtzRB1XDmxHSP7SoTstTaFys5FRuJy4SPxqrkJ0673NVUfWT/QXP/xP3MPTtTbwkOkqpAVVXcAxXQYAGycJ15pEuSVZsfTalNQ5z1kzbpRgOxUWpNm4g8kB1Alh/uyfgpEhLCuaGHaxryPBVfFE9poNaQgpYgdUv1FO3gu6zz6r80c2hoFa6SaE=
