language: python
sudo: false
branches:
  only:
    - master
    - /^\d\.\d+$/
    - /^\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 2.7
      env: TOXENV=jessie
    - python: 2.7
      env: TOXENV=pypy
    - python: 2.7
      env: TOXENV=pypy3
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
     - python: 3.6
       env: TOXENV=docs
install:
  - |
      if [ "$TOXENV" = "pypy" ]; then
        export PYPY_VERSION="pypy-6.0.0-linux_x86_64-portable"
        wget "https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2"
        tar -jxf ${PYPY_VERSION}.tar.bz2
        virtualenv --python="$PYPY_VERSION/bin/pypy" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
      if [ "$TOXENV" = "pypy3" ]; then
        export PYPY_VERSION="pypy3.5-5.9-beta-linux_x86_64-portable"
        wget "https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2"
        tar -jxf ${PYPY_VERSION}.tar.bz2
        virtualenv --python="$PYPY_VERSION/bin/pypy3" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
  - pip install -U tox twine wheel codecov

script: tox
after_success:
  - codecov
#notifications:
#  irc:
#    use_notice: true
#    skip_join: true
#    channels:
#    - irc.freenode.org#scrapy
notifications:
  slack:
    secure: LBkMhWd/pPjoWNdJj6CZvUDTYfMucqJwLYfpGmsU6sAlUbVRpr8O489wNxqJfxSWeA5nP3Xvkd7GvdSHtufGvozejYD68HcMXDVCcrLrD40bIXcEkmWvkwuIMVFjYcNXeMu+djt23FFeSAEC4djll3W6p6br7O6xBX+orfE9gHPyw2POVrjXkbZ4qDZGmWXfb9v7+0up+wI7wuMdlHY4drct2o7J34WzCQYLQItvWpPXuWgy3F5ERsxwECKpn0dLmNstMfi3szwL8wzKiPIgl3xtD661XCPowT8H0faucDOQn1KcQbey98izsLE/odt23F1D3a13gWYO8zHTkmNqyVZfVE2So7fpL6NujIZgjRJPNT9EfLS7HaJMqieUU2EQj7ZKi0BsZuO7EPDOQQkCOqCO12MkMHfPFGNJ/qWTGW5gwwMnV7Oezq6wZi/NdhwFY9+Q3iuz40vjotRVwigkS/qiSU4LagNiO/UzFrmBABKYv/TBAx0m7iWHsrtH1WKVvrrGb26/EMGYoCQt2tDtpm4hLEX1Qb7nPCqgYMOpWMofAN/Svr06JJIE2kxKkGaS5OgVY8r6VZTZjNXdzjKF19h7TPAv/8cHt39IBURz7rSlYdDMfSqQTg1VcSphR0QIL/HWt6wPEZt4/Y+LyUNkgRjE7lrUkra0zkmXRxRSSL4=
cache:
  directories:
    - $HOME/.cache/pip
# deploy:
#   provider: pypi
#   distributions: "sdist bdist_wheel"
#   user: scrapy
#   password:
#     secure: JaAKcy1AXWXDK3LXdjOtKyaVPCSFoCGCnW15g4f65E/8Fsi9ZzDfmBa4Equs3IQb/vs/if2SVrzJSr7arN7r9Z38Iv1mUXHkFAyA3Ym8mThfABBzzcUWEQhIHrCX0Tdlx9wQkkhs+PZhorlmRS4gg5s6DzPaeA2g8SCgmlRmFfA=
#   on:
#     tags: true
#     repo: scrapy/scrapy
#     condition: "$TOXENV == py27 && $TRAVIS_TAG =~ ^[0-9]+[.][0-9]+[.][0-9]+(rc[0-9]+|[.]dev[0-9]+)?$"
